services:
  mongo:
    image: mongo:4.4.6-bionic
    ports:
    - 27017:27017
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#      MONGO_INITDB_DATABASE: nest
